.\"     Title: TS_TEST
.\"    Author: Russell King
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: January 21, 2008
.\"    Manual: tslib
.\"    Source: Debian 1
.\"
.TH "TS_TEST" "1" "January 21, 2008" "Debian 1" "tslib"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ts_test \- A basic test routine for tslib.
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBts_test\fR, a basic test program for touch screens\&.
.PP
This manual page was written for the
Debian(TM)
distribution because the original program does not have a manual page\&.
.SH "SEE ALSO"
.PP
For more information on general tslib configuration, see
\fIts\&.conf\fR
(5) or for a quick summary of the environment variables, see
\fIts_calibrate\fR
(1)\&.
.SH "AUTHOR"
.PP
This manual page was written by Neil Williams
<codehelp@debian\&.org>
for the
Debian(TM)
system (but may be used by others)\&. Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
General Public License, Version 2 any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common\-licenses/GPL\&.
.SH "AUTHOR"
.PP
\fBRussell King\fR
.sp -1n
.IP "" 4
Author.
.SH "COPYRIGHT"
Copyright \(co 2008 Neil Williams
.br
